#!/usr/bin/env python3
"""Generate `docs/REST_API.md` from `.well-known/openapi.yaml`.

The prose docs previously described 7 of the 56 documented endpoints, and
nothing kept even those in step with the spec. Deriving the page from the spec
means it cannot drift: `--check` fails when the committed page differs from
what the current spec would produce, which is what CI runs.

Usage:
    python scripts/gen_api_reference.py           # write the page
    python scripts/gen_api_reference.py --check   # fail if it would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / ".well-known" / "openapi.yaml"
OUT = ROOT / "docs" / "REST_API.md"

METHODS = ("get", "post", "put", "patch", "delete")
UNTAGGED = "Other"


def request_fields(operation: dict) -> list[tuple[str, str, bool, str]]:
    """(name, type, required, description) for a JSON request body, if any."""
    schema = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema", {})
    )
    required = set(schema.get("required", []))
    fields = []
    for name, prop in (schema.get("properties") or {}).items():
        kind = prop.get("type", "object")
        if kind == "array":
            item = (prop.get("items") or {}).get("type", "object")
            kind = f"array[{item}]"
        fields.append((name, kind, name in required, prop.get("description", "")))
    return fields


def path_params(operation: dict, shared: list) -> list[tuple[str, str]]:
    """(name, description) for path parameters, spec-level and operation-level."""
    out = []
    for param in list(shared) + list(operation.get("parameters") or []):
        if param.get("in") == "path":
            out.append((param.get("name", "?"), param.get("description", "")))
    return out


def render(spec: dict) -> str:
    info = spec.get("info", {})
    lines: list[str] = [
        "<!-- Generated by scripts/gen_api_reference.py from .well-known/openapi.yaml.",
        "     Do not edit by hand -- edit the spec and regenerate. -->",
        "",
        "# REST API Reference",
        "",
        f"Version {info.get('version', 'unknown')} of the IronVault REST API.",
        "",
        "The API is behind the `api` cargo feature and is served by `iv serve`:",
        "",
        "```bash",
        "cargo build --release --features api",
        "iv serve --port 8080",
        "```",
        "",
        "Every endpoint below is prefixed as shown and returns JSON. Unless an",
        "endpoint is marked **no auth**, it requires a bearer token obtained from",
        "`POST /api/v1/auth/token`:",
        "",
        "```bash",
        'curl -sX POST localhost:8080/api/v1/auth/token \\',
        '  -H \'content-type: application/json\' \\',
        '  -d \'{"passphrase":"..."}\'',
        "```",
        "",
        "The machine-readable spec is served at `/api/v1/openapi.json` and lives at",
        "[`.well-known/openapi.yaml`](https://github.com/nervosys/IronVault/blob/master/.well-known/openapi.yaml).",
        "",
    ]

    # Group operations by tag, preserving a stable order.
    by_tag: dict[str, list[tuple[str, str, dict, list]]] = {}
    for path, item in (spec.get("paths") or {}).items():
        shared = item.get("parameters") or []
        for method in METHODS:
            operation = item.get(method)
            if not operation:
                continue
            tags = operation.get("tags") or [UNTAGGED]
            by_tag.setdefault(tags[0], []).append((path, method, operation, shared))

    total = sum(len(v) for v in by_tag.values())
    lines += [f"{total} operations across {len(by_tag)} groups.", ""]

    for tag in sorted(by_tag):
        lines += [f"## {tag}", ""]
        for path, method, operation, shared in sorted(by_tag[tag], key=lambda o: (o[0], o[1])):
            summary = operation.get("summary", "")
            # `security: []` at the operation level means the endpoint opts out
            # of the spec-level bearerAuth requirement.
            open_access = operation.get("security") == []
            heading = f"### `{method.upper()} {path}`"
            lines += [heading, ""]
            if summary:
                lines += [summary + ("" if summary.endswith(".") else "."), ""]
            if open_access:
                lines += ["**No auth** -- callable without a bearer token.", ""]

            params = path_params(operation, shared)
            if params:
                lines += ["Path parameters:", ""]
                for name, description in params:
                    lines.append(f"- `{name}`{' -- ' + description if description else ''}")
                lines.append("")

            fields = request_fields(operation)
            if fields:
                lines += ["Request body:", "", "| Field | Type | Required | Description |", "| --- | --- | --- | --- |"]
                for name, kind, required, description in fields:
                    lines.append(
                        f"| `{name}` | `{kind}` | {'yes' if required else 'no'} | {description or ''} |"
                    )
                lines.append("")

            responses = operation.get("responses") or {}
            if responses:
                lines += ["Responses:", ""]
                for code in sorted(responses):
                    description = (responses[code] or {}).get("description", "")
                    lines.append(f"- `{code}` -- {description}" if description else f"- `{code}`")
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = parser.parse_args()

    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))
    generated = render(spec)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print(
                f"{OUT.relative_to(ROOT)} is out of date with "
                f"{SPEC.relative_to(ROOT)}.\nRun: python scripts/gen_api_reference.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0

    OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
